show series db structure
datafruits/streampusher-api pull request #184
Opened 2022-10-03 17:39 UTC by mcfiredrill

2022-10-04 05:40 UTC, mcfiredrill commented on db/migrate/20220930192441_create_show_series.rb
> +      t.references :user, foreign_key: true
This could include VJs??

2022-10-05 02:36 UTC, dudethatbe requested changes

2022-10-05 02:36 UTC, dudethatbe commented on app/models/show_series.rb
> +
needs the scheduled_show relationship

2023-08-13 17:55 UTC, mcfiredrill commented on db/migrate/20230214030100_create_active_storage_tables.active_storage.rb
> +end
Prematurely added active storage stuff in this PR....not actually using any of it yet
TODO should remove

2023-10-01 18:52 UTC, merged